#!/usr/bin/env python3
"""Build flat system prompts (dist/system-prompt-{claude,gpt,deepseek}.md) from the skill files.

Usage:
    python scripts/build_prompt.py            write dist/
    python scripts/build_prompt.py --check    exit 1 if dist/ differs from fresh output

Sections are found by heading, so the script survives edits to the skill files.
Standard library only, Python 3.9+. Output is deterministic.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL_DIR = ROOT / "skills" / "tasteful-output"
DIST = ROOT / "dist"
MODELS = ("claude", "gpt", "deepseek")
CATEGORY_ORDER = ["L", "S", "C", "ST", "D", "F"]

HEADER = (
    "<!-- Generated by scripts/build_prompt.py. Do not edit; edit the skill files "
    "and re-run the script. -->"
)

# SKILL.md sections that do not apply to a flat prompt (matched against the heading text).
SKIP_SKILL_HEADINGS = re.compile(
    r"^(?:loading|workflow|taste[- ]?profile|taste[- ]?memory|the 5 checks|five checks|"
    r"file[- ]loading|references|setup)\b",
    re.I,
)

# Thresholds stated once here so the flat prompt always carries them (lead decision, round 1).
DENSITY = {
    "L13": "flag more than 2 era words per 500 words, or 2 in one paragraph",
    "F4": "flag more than 1 em dash per 250 words",
}
DENSITY_MARKERS = {"L13": "per 500 words", "F4": "per 250 words"}

VOICE_TEST = """## Voice test (after the checks pass)

1. Read it aloud. It should sound like a specific person, not a generic professional writer.
2. Keep at least one word or phrase the reader would not have predicted.
3. Vary sentence length: three sentences in a row should not share a length and shape.
4. Name the emotion in one or two words (wry, defiant, quietly confident). If you cannot name it, it is not there."""

CHECKLIST = """## Before you send

1. Every sentence survives the Substitution Test: swap in a competitor's name, and if it still works, rewrite it.
2. Every number, customer, quote and study came from the user or a source. Where a figure is missing, use a visible placeholder like [metric: X] and say so.
3. Review the draft against the pattern index in your own words, fix each hit with a specific fact, and send without describing the review."""

QUOTED_RE = re.compile(r'"[^"]*"|\u201c[^\u201d]*\u201d')

CODE_RE = r"[A-Z]{1,2}\d+"
HEADING_DEF_RE = re.compile(
    r"^(?:#{2,6}\s+|\*\*)(" + CODE_RE + r"):\s*(.+?)(?:\*\*)?\s*$"
)
TABLE_ROW_RE = re.compile(
    r"^\|\s*(" + CODE_RE + r")\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$"
)
BULLET_RE = re.compile(
    r"^\s*[-*]\s+\*\*(" + CODE_RE + r"):\s*(.+?)\*\*\s*(?:[—–:-]+\s*(.*))?$"
)


# ---------------------------------------------------------------- helpers
def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_frontmatter(text: str) -> str:
    if text.startswith("---"):
        m = re.match(r"---\s*\n.*?\n---\s*\n", text, re.S)
        if m:
            return text[m.end():]
    return text


def strip_links(text: str) -> str:
    """Turn [label](relative/path.md) into label; flat prompts have no files to link."""
    return re.sub(r"\[([^\]]+)\]\((?!https?://)[^)]*\)", r"\1", text)


def code_sort_key(code: str):
    m = re.match(r"([A-Z]+)(\d+)", code)
    cat, num = m.group(1), int(m.group(2))
    idx = CATEGORY_ORDER.index(cat) if cat in CATEGORY_ORDER else len(CATEGORY_ORDER)
    return (idx, cat, num)


def split_sections(text: str):
    """Yield (level, heading, body_lines) for each markdown heading, ignoring code fences."""
    sections = []
    cur = None
    fence = False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            fence = not fence
        m = None if fence else re.match(r"^(#{1,6})\s+(.*?)\s*$", line)
        if m:
            cur = [len(m.group(1)), m.group(2), []]
            sections.append(cur)
        elif cur is not None:
            cur[2].append(line)
    return sections


# ---------------------------------------------------------------- catalog parsing
def parse_index_file(path: Path) -> dict:
    """Return {code: (name, one_liner)} from table rows or router bullets in one file."""
    out = {}
    if not path.exists():
        return out
    for line in read(path).splitlines():
        m = TABLE_ROW_RE.match(line)
        if m:
            out[m.group(1)] = (m.group(2).strip(), m.group(3).strip())
            continue
        m = BULLET_RE.match(line)
        if m:
            out[m.group(1)] = (m.group(2).strip(), (m.group(3) or "").strip())
    return out


def catalog_index(skill_dir: Path = SKILL_DIR) -> dict:
    return parse_index_file(skill_dir / "anti-pattern-catalog.md")


def router_index(skill_dir: Path = SKILL_DIR) -> dict:
    out = {}
    pdir = skill_dir / "patterns"
    if pdir.is_dir():
        for p in sorted(pdir.glob("*.md")):
            out.update(parse_index_file(p))
    return out


def terminal_entries(skill_dir: Path = SKILL_DIR) -> list:
    """Return [{code, name, file, line, meta, body}] for every pattern heading in patterns/**.md.

    Duplicates are kept so check.py can report them. meta is the first non-blank line under
    the heading; body is the lines up to the next heading or horizontal rule.
    """
    out = []
    pdir = skill_dir / "patterns"
    if not pdir.is_dir():
        return out
    for p in sorted(pdir.rglob("*.md")):
        lines = read(p).splitlines()
        fence = False
        for i, line in enumerate(lines):
            if line.lstrip().startswith("```"):
                fence = not fence
            if fence:
                continue
            m = HEADING_DEF_RE.match(line)
            if not m:
                continue
            body = []
            for nxt in lines[i + 1:]:
                if re.match(r"^#{1,6}\s", nxt) or nxt.strip() == "---":
                    break
                body.append(nxt)
            meta = next((b.strip() for b in body if b.strip()), "")
            out.append({"code": m.group(1), "name": m.group(2).strip(), "file": p,
                        "line": i + 1, "meta": meta, "body": body})
    return out


def terminal_codes(skill_dir: Path = SKILL_DIR) -> dict:
    """Return {code: (name, file)}; first definition wins."""
    out = {}
    for e in terminal_entries(skill_dir):
        out.setdefault(e["code"], (e["name"], e["file"]))
    return out


def strip_quotes(text: str) -> str:
    """Remove quoted strings and tidy what is left; the index describes moves, not phrases."""
    t = QUOTED_RE.sub("", text)
    t = re.sub(r"\(\s*[,;]?\s*\)", "", t)
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"\s+([,.;:])", r"\1", t)
    t = re.sub(r"^[\s,;:\u2014\u2013-]+|[\s,;:\u2014\u2013-]+$", "", t)
    t = re.sub(r"[:,;]\s*(?=[:,;]|$)", "", t)
    t = re.sub(r"\s+", " ", t)
    return t.strip()


def diagnosis(code: str, skill_dir: Path = SKILL_DIR) -> str:
    for e in terminal_entries(skill_dir):
        if e["code"] != code:
            continue
        for ln in e["body"]:
            m = re.match(r"\*\*Why it's slop:\*\*\s*(.*)", ln.strip())
            if m:
                first = re.split(r"(?<=[.!?])\s+", strip_links(m.group(1)).strip())[0]
                return strip_quotes(first).rstrip(".")
    return ""


# Hand-written move descriptions where mechanical quote-stripping leaves a broken sentence.
# Used only when the catalog wording is too dependent on the quoted examples.
MOVE_OVERRIDES = {
    "L12": "Defining a thing by what it is not before saying what it is (not X but Y, more than X, rather than simply X); the contrast is cosmetic",
    "L16": "Fancy verbs standing in for plain is or has",
    "ST2": "Gesturing at unnamed alternatives instead of naming the actual competitor",
    "ST4": "A big count with no context about what was counted (sibling of ST7)",
    "D3": "A grid of logos with a vague trust caption and no stated relationship",
    "C3": "Praising or evaluating the question, or agreeing first, instead of answering it",
    "S3": "Transition lines that announce more content instead of moving the argument",
    "S4": "Testimonial cards wrapped in a line telling the reader to trust the quotes chosen",
    "S6": "A named framework (the N pillars of X) placed on a plain list",
    "S9": "A closing paragraph or recap phrase that restates what the reader just read",
    "L5": "Scene-setting throat-clearing before the point",
}

DANGLING = {"at", "to", "of", "in", "with", "a", "an", "the", "and", "or", "for", "than", "where", "is", "as"}


def _reads_whole(t: str) -> bool:
    """True when text left after quote removal still reads as a complete description."""
    words = t.split()
    return (len(words) >= 4 and t[:1].isupper() and words[-1].lower() not in DANGLING
            and not t.startswith("+") and not t.endswith("+"))


def compact_catalog(skill_dir: Path = SKILL_DIR) -> list:
    merged = dict(router_index(skill_dir))
    for code, val in catalog_index(skill_dir).items():
        merged[code] = val  # catalog table wins
    for code, (name, _f) in terminal_codes(skill_dir).items():
        merged.setdefault(code, (name, ""))
    lines = []
    for code in sorted(merged, key=code_sort_key):
        name, liner = merged[code]
        name = strip_quotes(strip_links(name)) or strip_links(name).strip('"')
        raw = strip_links(liner)
        liner = strip_quotes(raw)
        if QUOTED_RE.search(raw) and not _reads_whole(liner):
            liner = diagnosis(code, skill_dir) or liner
        elif len(liner.split()) < 3:
            liner = diagnosis(code, skill_dir) or liner
        if code in DENSITY and DENSITY_MARKERS[code] not in liner:
            liner = ("%s; %s" % (liner.rstrip(",;: "), DENSITY[code])) if liner else DENSITY[code]
        liner = MOVE_OVERRIDES.get(code, liner)
        lines.append("- %s %s: %s" % (code, name, liner) if liner else "- %s %s" % (code, name))
    return lines


# ---------------------------------------------------------------- prompt parts
def core_rules(skill_dir: Path = SKILL_DIR) -> str:
    text = strip_frontmatter(read(skill_dir / "SKILL.md"))
    out = []
    skip_level = None
    for level, heading, body in split_sections(text):
        if level == 1:
            continue
        if skip_level is not None:
            if level > skip_level:
                continue
            skip_level = None
        if SKIP_SKILL_HEADINGS.search(heading):
            skip_level = level
            continue
        block = "\n".join(body).strip("\n")
        out.append("%s %s\n\n%s" % ("#" * level, heading, strip_links(block)))
    return "\n\n".join(s.rstrip() for s in out)


def checks_section(skill_dir: Path = SKILL_DIR) -> str:
    """The 5 Checks section of SKILL.md verbatim (full pass criteria, scoring, Refine caveat)."""
    text = strip_frontmatter(read(skill_dir / "SKILL.md"))
    for level, heading, body in split_sections(text):
        if re.search(r"\b(?:5|five) checks\b", heading, re.I):
            block = strip_links("\n".join(body).strip("\n")).replace("**", "")
            return "## The 5 checks\n\n" + block
    sys.stderr.write("warning: no '5 Checks' section in SKILL.md; checks omitted\n")
    return ""


def profile_text(model: str, skill_dir: Path = SKILL_DIR) -> str:
    p = skill_dir / "profiles" / ("%s.md" % model)
    if not p.exists():
        sys.stderr.write("warning: %s missing; profile section omitted\n" % p)
        return ""
    for level, heading, body in split_sections(strip_frontmatter(read(p))):
        if level == 2 and heading.strip().lower() == "for the model":
            return strip_links("\n".join(body)).strip()
    sys.stderr.write("warning: %s has no '## For the model' section; nothing embedded\n" % p)
    return ""


def build(model: str, skill_dir: Path = SKILL_DIR) -> str:
    core = core_rules(skill_dir).replace("plus the catalog review", "plus the pattern index review") \
        .replace("and the catalog review", "and the pattern index review") \
        .replace("catalog review", "pattern index review")
    parts = [
        HEADER,
        "# Writing quality rules",
        core,
        checks_section(skill_dir),
        VOICE_TEST,
        "## Pattern index\n\nNamed slop patterns, each described by the move it makes. Other wordings of the "
        "same move count. After drafting, review the draft against this list and rewrite any hit with a "
        "specific fact.\n\n" + "\n".join(compact_catalog(skill_dir)),
    ]
    prof = profile_text(model, skill_dir)
    if prof:
        parts.append("## Model notes\n\n" + prof)
    parts.append(CHECKLIST)
    return "\n\n".join(p.strip("\n") for p in parts if p.strip()) + "\n"


def output_path(model: str) -> Path:
    return DIST / ("system-prompt-%s.md" % model)


def main(argv) -> int:
    check = "--check" in argv
    stale = []
    for model in MODELS:
        fresh = build(model)
        path = output_path(model)
        if check:
            if not path.exists() or read(path) != fresh:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            DIST.mkdir(exist_ok=True)
            path.write_text(fresh, encoding="utf-8", newline="\n")
            print("wrote %s" % path.relative_to(ROOT).as_posix())
    if check:
        if stale:
            print("dist/ is out of date: %s\nRun: python scripts/build_prompt.py" % ", ".join(stale))
            return 1
        print("dist/ is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
